---
- name: Postfix generate dh512 params.
  openssl_dhparam:
    path: "/etc/postfix/dh512.pem"
    size: 512
    owner: "root"
    group: "root"
    mode: 0640

- name: Postfix generate dh2048 params.
  openssl_dhparam:
    path: "/etc/postfix/dh2048.pem"
    size: 2048
    owner: "root"
    group: "root"
    mode: 0640

- name: Postfix template configuration files.
  template:
    src: "etc/postfix/{{ item.name }}.j2"
    dest: "/etc/postfix/{{ item.name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - name: "access_client.cidr"
      owner: "root"
      group: "root"
      mode: "0640"
    - name: "bogus_mx.cidr"
      owner: "root"
      group: "root"
      mode: "0640"
    - name: "helo_ip_hostname_check.pcre"
      owner: "root"
      group: "root"
      mode: "0640"
    - name: "main.cf"
      owner: "root"
      group: "root"
      mode: "0644"
    - name: "master.cf"
      owner: "root"
      group: "root"
      mode: "0640"
    - name: "mynetworks_table.cidr"
      owner: "root"
      group: "root"
      mode: "0640"
    - name: "mynetworks_table_intern.cidr"
      owner: "root"
      group: "root"
      mode: "0640"
    - name: "reject_bogus_ip.cidr"
      owner: "root"
      group: "root"
      mode: "0640"
  notify: restart postfix

- name: Postfix template aliases
  template:
    src: "etc/aliases.j2"
    dest: "/etc/aliases"
    owner: "root"
    group: "root"
    mode: 0644
  notify: postalias /etc/aliases
 
- name: Postfix template maps.
  template:
    src: "etc/postfix/{{ item }}.j2"
    dest: "/etc/postfix/{{ item }}"
    owner: "root"
    group: "root"
    mode: 0640
  loop: "{{ postfix_map_tables }}"
  notify: restart postfix

- name: Postfix postmap.
  command: "/usr/sbin/postmap /etc/postfix/{{ item }}"
  loop: "{{ postfix_map_tables }}"

- name: Ensure postfix is running and enabled.
  service:
    name: "postfix"
    state: "started"
    enabled: "yes"
