---
- name: create mesh bridges
  template:
    src: bridge.j2
    dest: "/etc/network/interfaces.d/{{ item.key }}BR"
  notify: reload network interfaces
  with_dict: "{{ meshes }}"

- name: set sysfs variables
  template:
    src: sysfs.j2
    dest: "/etc/sysfs.d/99-{{ item.key }}BR.conf"
  with_dict: "{{ meshes }}"
  notify: activate sysfs variables
