#!/usr/bin/ansible-playbook
---
- name: Manage DNS Internal Master Server.
  hosts: kichererbse.freifunk-mwu.de

  roles:
  - service-nginx
  - nodejs
  - yarn
  - geerlingguy.mysql
  - powerdns.pdns
  - pdns-admin

- name: Manage DNS External Master Server.
  hosts: linse.freifunk-mwu.de

  roles:
  - service-nginx
  - nodejs
  - yarn
  - geerlingguy.mysql
  - powerdns.pdns
  - pdns-admin
