#!/usr/bin/ansible-playbook
---
- import_playbook: gateways.yml
- import_playbook: monitoring.yml
- import_playbook: services.yml
- import_playbook: dns.yml
- import_playbook: buildservers.yml
- import_playbook: unifi.yml
- import_playbook: www.yml
- import_playbook: jitsi.yml
