#!/usr/bin/ansible-playbook
---
- name: Webservers
  hosts: www

  roles:
  - service-nginx-wordpress
  - service-nginx-etherpad
  - service-nginx-mwu-landing-page
  - service-nginx-firmware-selector
